---
sidebar: sidebar 
permalink: task-set-up-gcnv.html 
keywords: setup, set up, api, service account, requirements, permissions, google cloud netapp volumes, gcnv, bluexp. netapp console 
summary: NetApp Consoleには、Google Cloud NetApp Volumes API へのアクセスと、Google Cloud サービス アカウントを介した適切な権限が必要です。 
---
= Google Cloud NetApp Volumesを設定する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Consoleには、 Google Cloud サービス アカウントを介した適切な権限が必要です。

以下のタスクを完了して、NetApp ConsoleからGoogle Cloudプロジェクトにアクセスできるようにします。


NOTE: これらのタスクには、Google Cloud コンソールまたは gcloud CLI を使用できます。gcloud CLI を使用するには、最初にlink:https://cloud.google.com/sdk/docs/install-sdk["Google Cloud CLI をインストール済み"^]が必要です。

* 既存のサービス アカウントがない場合は、新しいアカウントを作成してください。
* なりすましのアクセスを許可します。
* 共有プロジェクトに IAM ロールを付与します。




== サービスアカウントを設定する


NOTE: Google Cloud プロジェクトの権限変更が反映されるまでには、数分かかる場合があります。

. Google Cloudコンソールでは、 https://console.cloud.google.com/iam-admin/serviceaccounts["サービスアカウントページに移動します"^] 。
. *プロジェクトを選択*をクリックし、プロジェクトを選択して*開く*をクリックします。
. サービス アカウントを作成するには、次の手順を実行します。
+
.. *サービス アカウントの作成*をクリックします。
.. サービス アカウント名 (フレンドリ表示名) と説明を入力します。
+
Google Cloud Console はこの名前に基づいてサービス アカウント ID を生成します。必要に応じて ID を編集します。後で ID を変更することはできません。

.. *作成して続行*をクリックします。
.. 役割リストから、* Google Cloud NetApp Volumes Admin * または * Google Cloud NetApp Volumes Viewer * ロールを選択します。
.. *続行*を選択します。
+
または、gcloud CLI を使用してロールを割り当てることもできます。

+
[source, cli]
----
gcloud projects add-iam-policy-binding <YOUR_PROJECT_ID> --member="serviceAccount:<YOUR_SA_EMAIL>" --role="roles/netapp.admin"
----
.. このサービス アカウントへの偽装アクセスを許可します: credentials-sa@wf-production-netapp.iam.gserviceaccount.com。詳細については、 https://cloud.google.com/iam/docs/create-short-lived-credentials-direct#sa-credentials-jwt["自己署名JSON Web Token（JWT）を作成する"^] 。
+
NetAppが所有するサービス アカウントは、そのサービス アカウントの秘密キーにアクセスすることなくそのサービス アカウントとして動作できるようにする、有効期間の短いアクセス トークンを要求するために使用されます。

+
または、gcloud CLI を使用して偽装アクセスを許可することもできます：

+
[source, cli]
----
gcloud iam service-accounts add-iam-policy-binding <YOUR_SA_EMAIL> --member="serviceAccount:credentials-sa@wf-production-netapp.iam.gserviceaccount.com" --role="roles/iam.serviceAccountTokenCreator" --project=<YOUR_PROJECT_ID>
----
+

NOTE: ステージング環境には、本番サービスアカウントの代わりに `credentials-sa@wf-staging-netapp.iam.gserviceaccount.com`を使用してください。上記のコマンドの `--member`パラメータ値を `serviceAccount:credentials-sa@wf-staging-netapp.iam.gserviceaccount.com`に置き換えてください。

.. ページの下部にある [*完了*] をクリックして、次の手順に進みます。






== 共有VPC

サービスアカウントを使用する追加の Google Cloud プロジェクトごとに、以下の手順を実行してください：

. _IAM ページ_ で、プロジェクト ドロップダウン メニューから共有 VPC ホスト プロジェクトを選択します。
. *プリンシパルの追加*をクリックします。
. [新しいプリンシパル] フィールドに、サービス アカウントのメール アドレスを入力します。
. [役割の選択] ドロップダウンから、* Google Cloud NetApp Volumes管理者* 役割を選択します。
. *保存*をクリックします。
+
または、gcloud CLI を使用して IAM ポリシーバインディングを追加することもできます：

+
[source, cli]
----
gcloud projects add-iam-policy-binding <SHARED_VPC_HOST_PROJECT_ID> --member="serviceAccount:<YOUR_SA_EMAIL>" --role="roles/netapp.admin"
----


詳細な手順については、Google Cloud のドキュメントを参照してください。

* link:https://cloud.google.com/iam/docs/creating-managing-service-accounts["サービス アカウントの作成と管理"^]
* link:https://cloud.google.com/iam/docs/roles-permissions/netapp["Google Cloud NetApp Volumes のロールと権限"^]
* link:https://cloud.google.com/iam/docs/granting-changing-revoking-access["リソースへのアクセスの許可、変更、取り消し"^]




== トラブルシューティング

エラーが発生した場合は、*iam.disableCrossProjectServiceAccountUsage* ポリシーが適用される場合があります。これを修正するには、次の手順を実行します。

. Google Cloud コンソールで、 https://console.cloud.google.com/iam-admin/orgpolicies["組織ポリシーページ"^] 。
. *プロジェクト間のサービス アカウントの使用を無効にする* ポリシーを見つけて無効にします。


.次の手順
link:task-add-roles.html["Google Cloud NetApp Volumes のロールを割り当てる"]。
