---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes' 
summary: NetApp ConsoleでのGoogle Cloud NetApp Volumesサポートの新機能について説明します。 
---
= 新着情報
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp ConsoleでのGoogle Cloud NetApp Volumesサポートの新機能について説明します。



== 2025年11月27日



=== Google Cloud Platform の認証情報の変更

お客様がより多くのGoogle Cloud NetApp Volumesシステムをセットアップして承認するにつれて、認証情報の管理方法が変わりました。

NetApp Volumes システムの認証情報は、Cloud Key Management サービスなどの Google クラウド バックエンドに保存されるようになり、新しいシステムを作成するときにサービス アカウントの偽装認証情報が使用されます。



== 2025年10月6日



=== BlueXPはNetApp Consoleになりました

NetApp Consoleは、強化され再構築されたBlueXP基盤上に構築され、オンプレミスとクラウド環境全体にわたるエンタープライズ グレードのNetAppストレージとNetApp Data Servicesの集中管理を提供し、リアルタイムの分析情報、より高速なワークフロー、および高度なセキュリティとコンプライアンスを備えた簡素化された管理を実現します。

変更内容の詳細については、link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp Consoleのリリースノート"] 。



== 2025年7月21日



=== BlueXPでのGoogle Cloud NetApp Volumesのサポート

BlueXPからGoogle Cloud NetApp Volumes を直接管理できるようになりました。

* 作業環境を追加します。
* ボリュームを表示します。
* 作業環境を削除します。

